os: osx

before_install:
  - brew install zsh
  - source $(curl -fsSL raw.githubusercontent.com/maurizzzio/dotfiles/master/install.zsh)

script:
  - dotfiles --help
    # vim
  - dotfiles vim
  - [[ ! -e ~/.vimrc ]] && exit 1
    # zsh
  - dotfiles zsh
  - source ~/.zshrc
  - ! functions gi && exit 1 

