language: objective-c
os: osx

before_install:
  - brew install zsh
  - curl -q https://raw.githubusercontent.com/maurizzzio/dotfiles/master/install.sh -o install.sh && source install.sh && rm install.sh

script:
  - dotfiles --help
