#!/bin/zsh

-install-vim-plug() {
  if [[ ! -e ${HOME}/.vim/autoload/plug.vim ]]; then
    curl -fLo ${HOME}/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  else
    print-message "vim-plug already installed"
  fi
}

dotfiles-vim() {
  print-header "vim"

  print-step "setting up directories..."
  mkdir -p ${HOME}/.vim 2> /dev/null

  print-step "installing macvim..."
  if ! formula-exists macvim; then
    brew install macvim --with-cscope --with-lua --with-override-system-vim --with-luajit --with-python3
  else
    print-message "macvim already installed"
  fi

  print-step "installing vim-plug..."
  -install-vim-plug

  print-step "vim symlinks..."
  symlink "vim/vimrc" "${HOME}/.vimrc"

  print-step "installing plugins..."
  vim +PlugInstall +qall
}

dotfiles-neovim() {
  print-header "neovim"

  print-step "setting up directories..."
  mkdir -p ${HOME/.config/nvim/autoload} 2> /dev/null

  print-step "installing vim-plug..."
  -install-vim-plug

  print-step "neovim symlinks..."
  symlink "neovim/init.vim" "${HOME}/.config/nvim/init.vim"
  symlink "neovim/UltiSnips" "${HOME}/.config/nvim/UltiSnips"
  symlink "neovim/spell" "${HOME}/.config/nvim/spell"

  # print-step "installing plugins..."
  # vim +PlugInstall +qall
}

