#!/bin/zsh

dotfiles-brew() {
  print-header "brew"

  print-step "installing formulas..."

  local formulas
  formulas=(
    ruby
    tree
    the_silver_searcher
  ) 
  for formula in $formulas; do
    brew install $formula
  done

  print-step "installing apps..."

  brew install caskroom/cask/brew-cask
  brew tap caskroom/versions
  brew tap caskroom/fonts
  brew cask install qlstephen qlmarkdown
  brew cask install iterm2
}

