#!/bin/zsh

dotfiles-vim() {
  print-header "vim"
  
  print-step "setting up directories..."
  mkdir -p ${HOME}/.vim 2> /dev/null

  print-step "installing macvim..."
  if ! formula-exists macvim; then
    brew install macvim --override-system-vim
  else
    print-message "macvim already installed"
  fi

  print-step "installing vim-plug..."
  if [[ ! -e ${HOME}/.vim/autoload/plug.vim ]]; then
    curl -fLo ${HOME}/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  else
    print-message "vim-plug already installed"
  fi

  print-step "vim symlinks..."
  symlink "vim/vimrc" "${HOME}/.vimrc"

  print-step "installing plugins..."
  vim +PlugInstall +qall
}

