#!/bin/zsh

dotfiles-python() {
  print-header "python"

  print-step "installing python..."
  brew install python

  # npm global modules
  print-step "installing python modules..."

  local modules
  modules=(
    grip              # preview markdown files
  )
  for module in $modules; do
    # pip is already installed on python +3.4
    pip install grip
  done
}

