#!/bin/zsh

-install-vim-plug() {
  if [[ ! -e $1 ]]; then
    curl -fLo $1 --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  else
    print-message "vim-plug already installed"
  fi
}

dotfiles-vim() {
  print-header "vim"

  print-step "setting up directories..."
  mkdir -p ${HOME}/.vim 2> /dev/null

  print-step "installing macvim..."
  if ! formula-exists macvim; then
    brew install macvim --with-cscope --with-lua --with-override-system-vim --with-luajit --with-python3
  else
    print-message "macvim already installed"
  fi

  print-step "installing vim-plug..."
  -install-vim-plug ${HOME}/.vim/autoload/plug.vim

  print-step "vim symlinks..."
  symlink "vim/vimrc" "${HOME}/.vimrc"

  print-step "installing plugins..."
  vim +PlugInstall +qall
}

dotfiles-neovim() {
  print-header "neovim"

  print-step "setting up directories..."
  mkdir -p ${HOME}/.config/nvim/{autoload,sessions,undo,plugged} 2> /dev/null

  print-step "installing neovim..."
  if ! formula-exists neovim; then
    brew install neovim/neovim/neovim
  else
    print-message "neovim already installed"
  fi

  print-step "install neovim pypi package..."
  pip install neovim

  print-step "installing vim-plug..."
  -install-vim-plug ${HOME}/.config/nvim/autoload/plug.vim

  print-step "neovim symlinks..."
  symlink "neovim/init.vim" "${HOME}/.config/nvim/init.vim"
  symlink "neovim/autoload/utils.vim" "${HOME}/.config/nvim/autoload/utils.vim"
  symlink "neovim/UltiSnips" "${HOME}/.config/nvim/UltiSnips"
  # symlink "neovim/spell" "${HOME}/.config/nvim/spell"

  print-step "installing plugins..."
  nvim +PlugInstall +qall

  # IMPORTANT
  # fix <C-h> not working well within nvim
  # see https://github.com/christoomey/vim-tmux-navigator/issues/61#issuecomment-87284887
}

