cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/versions'

if RUBY_PLATFORM =~ /darwin/
  brew 'ctags'
  brew 'fasd'
  brew 'figlet'
  brew 'fswatch'
  brew 'gist'
  brew 'hub'
  brew 'imgur-screenshot'
  brew 'rmtrash'
  brew 'tree'
  brew 'terminal-notifier'
  brew 'the_silver_searcher'
  brew 'wget'
  brew 'youtube-dl'

  # build system
  brew 'autoconf'
  brew 'automake'
  brew 'libtool'

  # casks
  tap 'caskroom/cask'
  tap 'caskroom/fonts'
  tap 'caskroom/versions'

  ## apps
  cask 'basictex'
  cask 'blender'
  cask 'cheatsheet'
  cask 'dash'
  cask 'flux'
  cask 'free-ruler'
  cask 'google-chrome'
  cask 'google-drive'
  cask 'google-photos-backup'
  cask 'iterm2'
  cask 'licecap'
  cask 'karabiner'
  cask 'skim'
  cask 'spotify'
  cask 'sublime-text3'
  cask 'tex-live-utility'
  cask 'the-unarchiver'
  cask 'utorrent'
  cask 'vlc'

  # https://github.com/sindresorhus/quick-look-plugins
  cask 'betterzipql'
  cask 'qlcolorcode'
  cask 'qlimagesize'
  cask 'qlmarkdown'
  cask 'qlprettypatch'
  cask 'qlstephen'
  cask 'quicklook-csv'
  cask 'quicklook-json'
  cask 'webpquicklook'
end
