let $VIMPATH = fnamemodify(resolve(expand('<sfile>:p')), ':h:h')
let $VARPATH = expand(('~/.cache'). '/vim')

" always loads relative to ./config/
function! s:source_file(path)
  let abspath = resolve(expand($VIMPATH.'/config/'.a:path))
  if filereadable(abspath)
    execute 'source ' fnameescape(abspath)
  endif
endfunction

" =====
" Setup
" =====

" add the ~/.dotfiles/neovim folder to the runtimepath
" NOTE: additional global functions are loaded from ./plugin
let &runtimepath.=','.escape(expand('$VIMPATH'), '\,')

" :h vim_starting
call s:source_file('base.vim')

" initialize plugins
call plug#begin('~/.config/nvim/plugged')
call s:source_file('plugin-setup.vim')
call plug#end()

filetype plugin indent on
syntax enable

call s:source_file('general.vim')
call s:source_file('plugin-mappings.vim')
call s:source_file('mappings.vim')
call s:source_file('theme.vim')
call s:source_file('autocommand.vim')

" alternative config
let abspath = resolve(expand($VIMPATH."alt.vim"))
if filereadable(abspath)
  execute 'source ' fnameescape(abspath)
endif

" vim: set ts=2 sw=2 tw=80 et :
