#!/bin/zsh

__warn() {
  printf "$(tput setaf 136)! %s(tput sgr0)" "$@"
}

# helper function to source file safely
__safe_source() {
  [[ -s $1 ]] && source $1 || echo "Trying to load '$1' but it doesn't exist"
}

########
# init #
########

# zsh options
# better handling of history duplicates
setopt HIST_IGNORE_ALL_DUPS
# 10 second wait if you do something that will delete everything
setopt RM_STAR_WAIT

#########
# zplug #
#########

source ${HOME}/.zplug/zplug

zplug "zsh-users/zsh-syntax-highlighting", nice:10
zplug "zsh-users/zsh-completions"
zplug "djui/alias-tips"
zplug "b4b4r07/enhancd", of:enhancd.sh
zplug "junegunn/fzf", do:"./install"

zplug "plugins/dirhistory", from:"oh-my-zsh"
zplug "plugins/git", from:"oh-my-zsh"
zplug "plugins/osx", from:"oh-my-zsh"

zplug "mafredri/zsh-async"
zplug "sindresorhus/pure"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load > /dev/null

#########################
# script initialization #
#########################

# fasd (https://github.com/clvv/fasd)
fasd_cache="${HOME}/.fasd-init-cache"
if [ "$(command -v fasd)" -nt "$fasd_cache" -o ! -s "$fasd_cache" ]; then
  fasd --init auto >| "$fasd_cache"
fi
source "$fasd_cache"
unset fasd_cache

# travis gem (https://github.com/travis-ci/travis.rb)
__safe_source ${HOME}/.travis/travis.sh

# fzf (https://github.com/junegunn/fzf)
#
# The following line is commented because fzf adds its own on install
# __safe_source ${HOME}/.fzf.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# n (https://github.com/tj/n)
export N_PREFIX="$HOME/n"
[[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).

# $DOTFILES_DIRECTORY is exported on ~/.zshenv
# see install.sh
__safe_source ${DOTFILES_DIRECTORY}/zsh/exports.zsh
__safe_source ${DOTFILES_DIRECTORY}/zsh/functions.zsh
__safe_source ${DOTFILES_DIRECTORY}/zsh/aliases.zsh

# Note: rvm must be sourced last or rvm will complain
__safe_source ${HOME}/.rvm/scripts/rvm

# remove functions from the global scope
unset -f __warn
unset -f __safe_source

# http://unix.stackexchange.com/questions/43601/how-can-i-set-my-default-shell-to-start-up-tmux
if command -v tmux>/dev/null; then
  [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && tmux
fi

